/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ValuVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getBenchmark"
      | "getComparisonResult"
      | "getMyFDV"
      | "hasSubmitted"
      | "submitFDV"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ComparisonCompleted" | "FDVSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBenchmark",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComparisonResult",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getMyFDV", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFDV",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBenchmark",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComparisonResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyFDV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitFDV", data: BytesLike): Result;
}

export namespace ComparisonCompletedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FDVSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValuVault extends BaseContract {
  connect(runner?: ContractRunner | null): ValuVault;
  waitForDeployment(): Promise<this>;

  interface: ValuVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getBenchmark: TypedContractMethod<[], [string], "view">;

  getComparisonResult: TypedContractMethod<[], [string], "view">;

  getMyFDV: TypedContractMethod<[], [string], "view">;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  submitFDV: TypedContractMethod<
    [encryptedFDV: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBenchmark"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getComparisonResult"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyFDV"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitFDV"
  ): TypedContractMethod<
    [encryptedFDV: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComparisonCompleted"
  ): TypedContractEvent<
    ComparisonCompletedEvent.InputTuple,
    ComparisonCompletedEvent.OutputTuple,
    ComparisonCompletedEvent.OutputObject
  >;
  getEvent(
    key: "FDVSubmitted"
  ): TypedContractEvent<
    FDVSubmittedEvent.InputTuple,
    FDVSubmittedEvent.OutputTuple,
    FDVSubmittedEvent.OutputObject
  >;

  filters: {
    "ComparisonCompleted(address)": TypedContractEvent<
      ComparisonCompletedEvent.InputTuple,
      ComparisonCompletedEvent.OutputTuple,
      ComparisonCompletedEvent.OutputObject
    >;
    ComparisonCompleted: TypedContractEvent<
      ComparisonCompletedEvent.InputTuple,
      ComparisonCompletedEvent.OutputTuple,
      ComparisonCompletedEvent.OutputObject
    >;

    "FDVSubmitted(address,uint256)": TypedContractEvent<
      FDVSubmittedEvent.InputTuple,
      FDVSubmittedEvent.OutputTuple,
      FDVSubmittedEvent.OutputObject
    >;
    FDVSubmitted: TypedContractEvent<
      FDVSubmittedEvent.InputTuple,
      FDVSubmittedEvent.OutputTuple,
      FDVSubmittedEvent.OutputObject
    >;
  };
}
